import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';
import logo from '../img/home/images1.jpeg';

const styles = StyleSheet.create({
    page: {
        padding: 30,
        fontFamily: 'Helvetica',
    },
    header: {
        marginBottom: 20,
        textAlign: 'center',
    },
    logo: {
        width: 100,
        height: 100,
        marginBottom: 10,
    },
    title: {
        fontSize: 18,
        marginBottom: 10,
    },
    sectionHeader: {
        backgroundColor: '#2E86C1',
        color: '#FFF',
        padding: 5,
        fontSize: 12,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    section: {
        marginBottom: 10,
        padding: 10,
        border: '1px solid #ddd',
        borderRadius: 5,
    },
    label: {
        fontSize: 12,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    value: {
        fontSize: 12,
        marginBottom: 5,
    },
    row: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    halfWidth: {
        width: '48%',
    },
    footer: {
        marginTop: 20,
        paddingTop: 10,
        borderTop: '1px solid #000',
        textAlign: 'center',
        fontSize: 10,
    },
});

const ComplaintPDF = ({ complaint }) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Image style={styles.logo} src={logo} />
                <Text style={styles.title}>CUSTOMER COMPLAINT FORM</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionHeader}>USER INFORMATION</Text>
                <View style={styles.row}>
                    <View style={styles.halfWidth}>
                        <Text style={styles.label}>Username:</Text>
                        <Text style={styles.value}>{complaint.user || 'N/A'}</Text>
                    </View>
                    <View style={styles.halfWidth}>
                        <Text style={styles.label}>Email:</Text>
                        <Text style={styles.value}>{complaint.email || 'N/A'}</Text>
                    </View>
                </View>
                <View style={styles.row}>
                    <View style={styles.halfWidth}>
                        <Text style={styles.label}>Phone:</Text>
                        <Text style={styles.value}>{complaint.phone || 'N/A'}</Text>
                    </View>
                </View>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionHeader}>COMPLAINT INFORMATION</Text>
                <View style={styles.row}>
                    <View style={styles.halfWidth}>
                        <Text style={styles.label}>Complaint Date:</Text>
                        <Text style={styles.value}>{complaint.date || 'N/A'}</Text>
                    </View>
                </View>
                <Text style={styles.label}>Complaint Title:</Text>
                <Text style={styles.value}>{complaint.title}</Text>
                {/* <Text style={styles.label}>Complaint Details:</Text>
                <Text style={styles.value}>{complaint.details}</Text> */}
                <Text style={styles.label}>complaint Details:</Text>
                <Text style={styles.value}>{complaint.issue}</Text>
            </View>

            <View style={styles.section}>
                <Text style={styles.sectionHeader}>ASSIGNED WORKER</Text>
                <Text style={styles.label}>Assigned Worker:</Text>
                <Text style={styles.value}>{complaint.assignedWorker || 'N/A'}</Text>
                <Text style={styles.label}>Status:</Text>
                <Text style={styles.value}>{complaint.status}</Text>
            </View>

            <View style={styles.footer}>
                <Text>Generated by Complaint Management System</Text>
            </View>
        </Page>
    </Document>
);

export default ComplaintPDF;
